services:
  # 1. The Python Agent (UI + Logic)
  - type: web
    name: parallax-agent
    runtime: docker
    rootDir: py-agent
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8501
      # We use the internal service name and port here
      - key: GO_SCRAPER_URL
        value: http://parallax-scraper:8080/scrape
      - key: DATABASE_URL
        fromDatabase:
          name: parallax-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false

  # 2. The Go Scraper (Backend Helper)
  - type: web
    name: parallax-scraper
    runtime: docker
    rootDir: go-scraper
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080

databases:
  # 3. The Memory
  - name: parallax-db
    databaseName: parallax_core
    user: parallax_user
    plan: free
    ipAllowList: []