services:
  # 1. The Python Agent (UI + Logic)
  # This is the one you will click on to use the app.
  - type: web
    name: parallax-agent
    runtime: docker
    rootDir: py-agent          # LOOK HERE: We tell it to go into the python folder
    dockerfilePath: Dockerfile # And find the file named Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8501
      - key: GO_SCRAPER_URL
        fromService:
          type: web
          name: parallax-scraper
          property: url
      - key: DATABASE_URL
        fromDatabase:
          name: parallax-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false

  # 2. The Go Scraper (Backend Helper)
  # You never visit this URL. The Python agent visits it for you.
  - type: web
    name: parallax-scraper
    runtime: docker
    rootDir: go-scraper        # LOOK HERE: We tell it to go into the go folder
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080

databases:
  # 3. The Memory
  - name: parallax-db
    databaseName: parallax_core
    user: parallax_user
    plan: free
    ipAllowList: []